# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:
    BorderZero:
        convention: none
    PropertySortOrder:
        order: smacss
    Indentation:
        width: 4
    QualifyingElement:
        allow_element_with_attribute: true
        allow_element_with_class: true
        allow_element_with_id: true
    LeadingZero:
        style: include_zero
    StringQuotes:
        style: double_quotes
