# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:
    BorderZero:
        convention: none
    PropertySortOrder:
        order: smacss
    Indentation:
        width: 4
