title: Blue Husky Stylesheets
email: BenLeggiero@Gmail.com
description: >- # this means to ignore newlines until the next property
  A bunch of stylesheets that power Blue Husky products
theme: jekyll-theme-minimal
sass:
    style: expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # style: compressed
    compile_in_place: true
    load_paths:
        - assets
        - assets/v2/basics
        - assets/v2/structure
        - assets/v2/material
        - assets/v2/neon
        - assets/v2/3p/css-vars
    sass_dir: assets
twitter_username: BenLeggiero
github_username:  BenLeggiero
