---
title: Blue Husky Stylesheets
email: KyLeggiero@Gmail.com
description: >- # this means to ignore newlines until the next property
  A bunch of stylesheets that power Blue Husky products
theme: jekyll-theme-minimal
sass:
    style: expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    compile_in_place: true  # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory
    load_paths:
        - assets
        - assets/v2/basics
        - assets/v2/general
        - assets/v2/structure
        - assets/v2/material
        - assets/v2/neon
        - assets/v2/neon/elements
        - assets/v2/3p/css-vars
        - assets/v2/3p/Font-Awesome/scss
    sass_dir: assets
twitter_username: KyLeggiero
github_username: KyLeggiero
